# Application
spring.application.name=relayhook

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://172.25.192.1:5433/relayhooks}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}
spring.devtools.restart.enabled=true

# (Optional) JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true 


spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.default-receive-queue=workflow.node.execute

spring.relayhook.baseurl=http://172.25.192.1:5000