spring.application.name=relayhook

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/relayhooks}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}
spring.devtools.restart.enabled=true

# (Optional) JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true 


spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.default-receive-queue=workflow.node.execute

spring.relayhook.baseurl=http://localhost:5000

spring.jwt.secret=cmdjkvemvcdc1d6v54fvrg7grt8564r3r5322f54566><.df!4d58...055df!!#4
spring.jwt.secret.two=cmdjkvemvcdc1d6v54fvrg7grt8564r3r5322f54566><.df!4d58...055df!!#4

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=support@relayhook.in
spring.mail.password=Queengambit01!
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000
spring.mail.properties.mail.debug=true