# Application
spring.application.name=relayhook

spring.datasource.url=jdbc:postgresql://postgres:5432/relayhooks
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}
spring.devtools.restart.enabled=true

# (Optional) JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true 


spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=relayuser
spring.rabbitmq.password=relaypass
spring.rabbitmq.template.default-receive-queue=workflow.node.execute

spring.relayhook.baseurl=http://relay-hooks-node:5000

spring.jwt.secret=cmdjkvemvcdc1d6v54fvrg7grt8564r3r5322f54566><.df!4d58...055df!!#4
spring.jwt.secret.two=cmdjkvemvcdc1d6v54fvrg7grt8564r3r5322f54566><.df!4d58...055df!!#4

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.frommail=support@surgeit.co.in
spring.mail.username=93329c002@smtp-brevo.com
spring.mail.password=xsmtpsib-6ccc0754958db915e20dbb530dcf609c0f356a67589826ae9a1fba094dda364d-t2tQtk9U0vPyCbvf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.apikey=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
