# Application
spring.application.name=relayhook

# DataSource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/relayhooks_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update   # auto-create/update tables
spring.jpa.show-sql=true               # log SQL statements
spring.jpa.properties.hibernate.format_sql=true
